# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

Style/MethodName:
  Exclude:
  # the mocked Update module methods break the Ruby naming rule
  - test/main_workflow_test.rb
